### PR TITLE
Turkish translation

### LINKED ISSUE #50: Problem with 404 ru
1. Open http://ugene.net/hpc.html.
2. Click "Русский" at the bottom of the page. The 404 page will open.
3. Click "Русский" several times. The search bar will contain a link similar to http://ugene.net/ru/ru/ru/ru/ru/ru/ru/ru/hpc.html.

### PR DESCRIPTION
**Pull request by evelinabis**
Need to check the tr/download page (not download-all) that the translations are correct (taking into account the header).

### CODE REVIEW

**Review by yalgaer — CHANGES_REQUESTED** [review]
Here is the bug:
Open http://localhost:4000/changelist.html
Click to the Turkish translation link: you will see 'page not found'

Since we do not have 1:1 pages for Turkish (as we have for En & Ru)  I would suggest to always go to the Turkish start page when user clicks 'Turkish' link.

**Comment by evelinabis** [comment]
Dear @serkan-maker,

Thank you for the improvement. Could you review the changes in the current pull request? I added several files to your translation for better compatibility, for this I needed to translate some phrases into Turkish (for example, [footer.html](https://github.com/ugeneunipro/ugeneunipro.github.io/pull/61/files#diff-ee054816f6131de455f527cdb0bca362d7d3b2f865e50da41dbbf694c4177480R14), [header.html](https://github.com/ugeneunipro/ugeneunipro.github.io/pull/61/files#diff-ae15b9d7c7c552e1c83535c8035ad5ce4b130466e9ca7f20c06a190815f91f05), [download](https://github.com/ugeneunipro/ugeneunipro.github.io/pull/61/files#diff-a10e79649b424dea4dfb4a7a1ca3d75392c1a85a4e990b80f9fd406a29641c4a)). Please make sure everything is spelled correctly. It is especially important to me that you take a look at [the attached page](https://github.com/ugeneunipro/ugeneunipro.github.io/files/8580280/Download.zip). Let me know if any words/phrases need to be changed.

Thank you for help.
Best regards,
Evelina,
The UGENE team.

**Comment by serkan-maker** [comment]
Hi.EvelinaBiserova
only two sentences need correction
[docs/_includes/tr/header.html ](https://github.com/ugeneunipro/ugeneunipro.github.io/pull/61/files#diff-ae15b9d7c7c552e1c83535c8035ad5ce4b130466e9ca7f20c06a190815f91f05)
>Bağış yapmak>  **actually  ( Bağış yap)**
>Hata izci>   **actually  (Hata izleyici)**

**Review by yalgaer — APPROVED** [review]
Looks good

**Pull request merged**
